---
  - name: ensure apt cache is up to date
    yum: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

